### ISSUE TITLE
Could not pass event PlayerRespawnEvent

### ISSUE THREAD

**Issue by Siriuo** [masagameplay/MaSuiteTeleports#15]
Getting the below error when player respawns.

https://pastebin.com/FAg40mc9

**Comment by Resi23** [comment]
same here git-Paper-136 (MC: 1.14.4)

[20:20:41] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to MaSuiteTeleports v1.3.4.8
java.lang.NullPointerException: null
	at fi.matiaspaavilainen.masuiteteleports.bukkit.MaSuiteTeleports.onDeath(MaSuiteTeleports.java:85) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor478.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-136]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-136]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:671) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:596) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2071) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:31) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by masagameplay** [comment]
The latest dev builds (https://ci.codemc.org/job/masagameplay) fixes all known issues from every MaSuite plugin.

**Comment by LysergikProductions** [comment]
This issue is occurring for me using paper 1.16.5#588 and some other plugins.

```
12.04 05:47:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
12.04 05:47:04 [Server] ERROR Could not pass event PlayerRespawnEvent to RandomSpawnPlus v3.4.4
12.04 05:47:04 [Server] INFO java.lang.NullPointerException: null
12.04 05:47:04 [Server] INFO at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.16.5.jar:git-Paper-589]
12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.checkSpawn(SpawnFinder.java:167) ~[?:?]
12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.getValidLocation(SpawnFinder.java:119) ~[?:?]
12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.findSpawn(SpawnFinder.java:132) ~[?:?]
12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.listeners.RSPDeathListener.onDeath(RSPDeathListener.java:45) ~[?:?]
12.04 05:47:04 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
12.04 05:47:04 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-589]
```

**Comment by masagameplay** [comment]
> 
> 
> This issue is occurring for me using paper 1.16.5#588 and some other plugins.
> 
> ```
> 12.04 05:47:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
> 12.04 05:47:04 [Server] ERROR Could not pass event PlayerRespawnEvent to RandomSpawnPlus v3.4.4
> 12.04 05:47:04 [Server] INFO java.lang.NullPointerException: null
> 12.04 05:47:04 [Server] INFO at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.16.5.jar:git-Paper-589]
> 12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.checkSpawn(SpawnFinder.java:167) ~[?:?]
> 12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.getValidLocation(SpawnFinder.java:119) ~[?:?]
> 12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.spawn.SpawnFinder.findSpawn(SpawnFinder.java:132) ~[?:?]
> 12.04 05:47:04 [Server] INFO at systems.kscott.randomspawnplus3.listeners.RSPDeathListener.onDeath(RSPDeathListener.java:45) ~[?:?]
> 12.04 05:47:04 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
> 12.04 05:47:04 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-589]
> ```
This issue is caused by RandomSpawnPlus. It's [SpigotMC resource page](https://www.spigotmc.org/resources/randomspawnplus-optimized-wild-and-random-spawn-1-8-x-1-15-x.69586/) has links to their support channels.
