### ISSUE TITLE
spawn command not work correctly

### ISSUE THREAD

**Issue by Dakir22** [masagameplay/MaSuiteTeleports#16]
Hi, my spawn command doesn't work right. If a player is on a server other than the one where the spawn point is set and he enters /spawn, he will be teleported to the server but not to the spawn point but to the last point where the player was on that server.

So as an example:
Player A is on server A and the spawn point is on server B. If player A now enters /spawn he will be connected to server B but not teleported to the spawn point.
If there is also no other player on server A and the user returns to server A after the faulty spawn teleport, this error occurs in the console:
<details>
  <summary>ERROR</summary>
  [21:41:08 WARN]: [MaSuiteTeleports] Task #650 for MaSuiteTeleports v1.3.5 generated an exception
java.lang.IllegalArgumentException: location.world
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-156]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:742) ~[patched_1.14.4.jar:git-Paper-156]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489) ~[patched_1.14.4.jar:git-Paper-156]
at fi.matiaspaavilainen.masuiteteleports.bukkit.listeners.TeleportListener.lambda$onPluginMessageReceived$4(TeleportListener.java:83) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-156]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-156]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-156]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
</details>

If there is still player B on server A, this error does not occur in the console, but player A is still not teleported correctly to the spawn.

I use the latest dev builds from MaSuite(Core, Warps, Teleports, Portals, Homes) and the latest builds from Paper and Waterfall 1.14.4.

I hope you understand what I mean.

**Comment by masagameplay** [comment]
Thank you for reporting this. [The latest dev build](https://ci.codemc.org/job/masagameplay/job/MaSuiteTeleports/) should fix this issue. Now you can adjust the time before teleportation order is sent to the server from BungeeCord (plugins/MaSuite/teleports/settings.yml).

**Comment by Dakir22** [comment]
Thanks a lot, now works perfectly
