### ISSUE TITLE
Spawn on join is throwing an error when second player joins

### ISSUE THREAD

**Issue by masagameplay** [masagameplay/MaSuiteTeleports#23]
The first join seems to be working when `spawn-on-join: true` but the second player is throwing an error: 

```
[12:06:24 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@64a8c844, id=101, owner=dev.masa.masuiteteleports.bungee.MaSuiteTeleports@480cbe2e, task=dev.masa.masuiteteleports.bungee.listeners.PlayerJoinEvent$$Lambda$616/524485164@3f2ae361, delay=750, period=0, running=true) encountered an exception java.lang.NullPointerException: null
     at dev.masa.masuiteteleports.core.services.SpawnService.teleportToSpawn(SpawnService.java:33) ~[?:?]
     at dev.masa.masuiteteleports.bungee.listeners.PlayerJoinEvent.lambda$onJoin$0(PlayerJoinEvent.java:34) ~[?:?]         
     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:a16947e:318]         
     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_131]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_131]         
     at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

When keep-request-alive: 1 #In seconds, the error disappears and spawn-on-join: true is valid, but the player accept time is too short.

**Comment by masagameplay** [comment]
Should be fixed already.
