### ISSUE TITLE
Plugin are completely off on 1.12.2

### ISSUE THREAD

**Issue by fengyuan213** [masagameplay/MaSuiteTeleports#40]
I am running Ma's teleport with 1.12.2 servers. The waterfall is able to load normally but the spigot/catserver/Mohist version doesn't. All the MaSuite plugins are properly installed and configured. But it shows the following stacktrace at the startup.

[23:23:17] [Server thread/ERROR]: Could not load 'plugins\MaSuitePortals.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-92b87c7]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:344) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at dev.masa.masuiteportals.bukkit.MaSuitePortals.<init>(MaSuitePortals.java:28) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[PluginClassLoader.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-92b87c7]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[PluginClassLoader.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-92b87c7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at dev.masa.masuiteportals.bukkit.MaSuitePortals.<init>(MaSuitePortals.java:28) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[PluginClassLoader.class:git-CatServer-1.12.2-92b87c7]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-92b87c7]
        ... 7 more

**Comment by masagameplay** [comment]
MaSuitePortals only works for 1.13+.
