### ISSUE TITLE
'~' not working in /tpnot working in /tp

### ISSUE THREAD

**Issue by henkelmax** [masagameplay/MaSuiteTeleports#8]
The '~' is not working in the /tp command.
It is causing an exception:

```
[19:02:42 WARN]: [MaSuiteTeleportsBridge] Plugin MaSuiteTeleportsBridge v1.3.4.6 generated an exception while executing task 615
java.lang.NumberFormatException: For input string: "~"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_171]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_171]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_171]
	at fi.matiaspaavilainen.masuiteteleports.commands.force.Teleport.lambda$onCommand$1(Teleport.java:86) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_server.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_server.jar:git-Spigot-518206a-a5b9c7b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by masagameplay** [comment]
Hello,

Currently MaSuiteTeleports does not support for ~. This might be added in the future. If you need to use ~, you can use /minecraft:tp.

**Comment by henkelmax** [comment]
It would at least be good to hide this exception and give a response to the player

**Comment by masagameplay** [comment]
Yeah, it would. I had not thought this when I made the tp command but still it should give error message "Invalid coordinates" if the values are not numbers.

**Comment by T9C5F** [comment]
Yep,
> You have already a command in progress, try it again in few seconds

is rather misleading. ;-)

**Comment by masagameplay** [comment]
> Yep,
> 
> > You have already a command in progress, try it again in few seconds
> 
> is rather misleading. ;-)

Interesting, will be fixed and added in the next update.
